export const defaultStrings = {
    sizeLabel: 'Size:',
    newGame: 'New Game',
    end: 'End',
    settings: 'Settings',
    boardSize: 'Board size',
    colorScheme: 'Color scheme',
    save: 'Save',
    confirm: 'Confirm',
    cancel: 'Cancel',
    settingsResetWarning: 'Changing the board size will reset your current game.',
    themeDefault: 'Default',
    themeClassic: 'Classic',
    themeClassicDark: 'Classic dark',
    gameOver: 'Game over!',
    score: 'Score',
    best: 'Best',
    website: 'Portfolio website',
    githubProfile: 'GitHub profile',
}
