export {default as settingsIcon} from '@iconify-icons/mdi/cog'
export {default as closeIcon} from '@iconify-icons/mdi/close'
export {default as thumbUpIcon} from '@iconify-icons/mdi/thumb-up'
export {default as webIcon} from '@iconify-icons/mdi/web'
export {default as githubIcon} from '@iconify-icons/simple-icons/github'
